services:
  backend:
    build: ./backend
    ports:
      - "4101:4101"
    environment:
      PORT: 4101
      CORS_ORIGIN: http://127.0.0.1:5171
      DB_FILE: /app/data/app-db.json
    volumes:
      - ./data:/app/data
  frontend:
    build: ./frontend
    ports:
      - "5101:80"
    depends_on:
      - backend

